Ttree:
  ContentRepositoryImporter:
    sources:
      default:
        host: db
        driver: pdo_mysql
        dbname: db
        user: admin
        password: pass
        charset: UTF8
    presets:
      'base':
        'groups':
          label: 'Import Groups'
          dataProviderClassName: 'Ws\FshImport\DataProvider\GroupDataProvider'
          importerClassName: 'Ws\FshImport\GroupImporter'
          importerOptions:
            targetNode: 'g'
            siteNodePath: '/sites/fshsite'
        'groupContent':
          label: 'Import Groups'
          dataProviderClassName: 'Ws\FshImport\DataProvider\GroupContentDataProvider'
          importerClassName: 'Ws\FshImport\GroupContentImporter'
          importerOptions:
            siteNodePath: '/sites/fshsite'
