
Neos:
  Demo:
    flickr:
      tagStreamUriPattern: 'http://api.flickr.com/services/feeds/photos_public.gne?format=json&nojsoncallback=1&tags=%s'
      userStreamUriPattern: 'http://api.flickr.com/services/feeds/photos_public.gne?format=json&nojsoncallback=1&id=%s'
  Flow:
    i18n:
      defaultLocale: de
      fallbackRule:
        order:
          - de
  Form:
    yamlPersistenceManager:
      savePath: 'resource://Ws.Fshsite/Private/Form/'
    presets:
      bootstrap:
        title: 'Twitter bootstrap'
        parentPreset: default
        formElementTypes:
          'Neos.Form:Base':
            renderingOptions:
              layoutPathPattern: 'resource://Ws.Fshsite/Private/Templates/ContactForm/{@type}.html'
          'Neos.Form:FormElement':
            properties:
              elementClassAttribute: form-control
          'Neos.Form:MultiLineText':
            properties:
              elementClassAttribute: form-control
  Neos:
    userInterface:
      editPreviewModes:
        print:
          isEditingMode: false
          isPreviewMode: true
          typoScriptRenderingPath: print
          title: 'Neos.Demo:Main:editPreviewModes.print'
          position: 200
      translation:
        autoInclude:
          Ws.Fshsite:
            - Main
            - 'NodeTypes/*'
      inspector:
        dataTypes:
          Neos\Media\Domain\Model\ImageInterface:
            editorOptions:
              features:
                resize: true
      defaultLanguage: de
Networkteam:
  Neos:
    Shariff:
      options:
        services:
          - Twitter
          - Facebook
          - GooglePlus
DL:
  Gallery:
    loadGalleryCSS: true
    loadGalleryJS: true
    themes:
      bootstrapLightbox:
        label: 'Bootstrap with Lightbox'
        themeSettings:
          columnClass: col-sm-4
          imageVariants:
            thumb:
              maximumWidth: null
              maximumHeight: null
              width: 600
              height: 600
              allowCropping: true
              allowUpScaling: null
            large:
              maximumWidth: 2000
              maximumHeight: 1200
              width: null
              height: null
              allowCropping: null
              allowUpScaling: null
Sandstorm:
  UserManagement:
    activationTokenTimeout: '2 days'
    confirmationTokenTimeout: '8 weeks'
    resetPasswordTokenTimeout: '4 hours'
    authFailedMessage:
      title: 'Login nicht möglich'
      body: 'Sie haben ungültige Zugangsdaten eingegeben. Bitte versuchen Sie es noch einmal.'
    email:
      senderAddress: keine-antwort@frauenselbsthilfe.de
      senderName: 'Webseiten Account'
      confirmationAddress: stefan.johaenntgen@webservus.de
      confirmationName: Mitgliedsverwaltung
      subjectConfirmation: 'Account prüfen'
      subjectActivation: 'Account bestätigen'
      subjectResetPassword: 'Passwort neu setzen'
      templatePackage: Ws.Fshsite
    rolesForNewUsers: {  }
    redirect:
      afterLogin: {  }
      afterLogout: {  }
