
Neos:
  Demo:
    flickr:
      tagStreamUriPattern: 'http://api.flickr.com/services/feeds/photos_public.gne?format=json&nojsoncallback=1&tags=%s'
      userStreamUriPattern: 'http://api.flickr.com/services/feeds/photos_public.gne?format=json&nojsoncallback=1&id=%s'
  Flow:
    i18n:
      defaultLocale: de
      fallbackRule:
        order:
          - de
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              Sandstorm.UserManagement:NeosBackend:
                pattern: Sandstorm\UserManagement\Security\NeosRequestPattern
                patternOptions:
                  'area': 'backend'
          'Sandstorm.UserManagement:Login':
            provider: PersistedUsernamePasswordProvider
            requestPatterns:
              Sandstorm.UserManagement:NeosFrontend:
                pattern: Sandstorm\UserManagement\Security\NeosRequestPattern
                patternOptions:
                  'area': 'frontend'
  Form:
    yamlPersistenceManager:
      savePath: 'resource://Ws.Fshsite/Private/Form/'
    presets:
      bootstrap:
        title: 'Twitter bootstrap'
        parentPreset: default
        formElementTypes:
          'Neos.Form:Base':
            renderingOptions:
              layoutPathPattern: 'resource://Ws.Fshsite/Private/Templates/ContactForm/{@type}.html'
          'Neos.Form:FormElement':
            properties:
              elementClassAttribute: form-control
          'Neos.Form:MultiLineText':
            properties:
              elementClassAttribute: form-control
  Neos:
    userInterface:
      editPreviewModes:
        print:
          isEditingMode: false
          isPreviewMode: true
          typoScriptRenderingPath: print
          title: 'Print'
          position: 200
      translation:
        autoInclude:
          Ws.Fshsite:
            - Main
            - 'NodeTypes/*'
      inspector:
        dataTypes:
          Neos\Media\Domain\Model\ImageInterface:
            editorOptions:
              features:
                resize: true
      defaultLanguage: de
Networkteam:
  Neos:
    Shariff:
      options:
        services:
          - Twitter
          - Facebook
          - GooglePlus
DL:
  Gallery:
    loadGalleryCSS: true
    loadGalleryJS: true
    themes:
      bootstrapLightbox:
        label: 'Bootstrap with Lightbox'
        themeSettings:
          columnClass: col-sm-4
          imageVariants:
            thumb:
              maximumWidth: null
              maximumHeight: null
              width: 600
              height: 600
              allowCropping: true
              allowUpScaling: null
            large:
              maximumWidth: 2000
              maximumHeight: 1200
              width: null
              height: null
              allowCropping: null
              allowUpScaling: null

Sandstorm:
  UserManagement:
    # Validity timespan for the activation token for newly registered users.
    activationTokenTimeout: '2 days'
    # Validity timespan for the token used to reset passwords.
    resetPasswordTokenTimeout: '4 hours'
    # The message that appears if a user could not be logged in.
    authFailedMessage:
      title: 'Login nicht möglich'
      body: 'Sie haben ungültige Zugangsdaten eingegeben. Bitte versuchen Sie es noch einmal.'
    # Email settings
    email:
      # Subject line for the account confirmation email
      subjectActivation: 'Account bestätigen'
      # Subject line for the password reset email
      subjectResetPassword: 'Passwort neu setzen'
    # An array of roles which are assigned to users after they activate their account.
    rolesForNewUsers: []
  TemplateMailer:
    templatePackages:
      10: 'Ws.Fshsite'
    senderAddresses:
      sandstorm_usermanagement_sender_email: # You need to use this exact key to override the UserManagement defaults
        name: 'Webseiten Account'
        address: 'keine-antwort@frauenselbsthilfe.de'
